In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

from pathlib import Path
path=Path(os.getcwd())
dir=path.parent.absolute()

C:\Users\deepa\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\deepa\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\deepa\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %

In [4]:
# data link: https://ibdmdb.org/tunnel/public/summary.html
filename=os.path.join(dir,"NIH_data\\hmp2_metadata.csv")
df = pd.read_csv(filename)
print(df.head)

<bound method NDFrame.head of            Project External ID Participant ID site_sub_coll   data_type  \
0     C3001CSC1_BP      206615          C3001     C3001CSC1  biopsy_16S
1     C3001CSC2_BP      206614          C3001     C3001CSC2  biopsy_16S
2     C3002CSC1_BP      206617          C3002     C3002CSC1  biopsy_16S
3     C3002CSC2_BP      206619          C3002     C3002CSC2  biopsy_16S
4     C3002CSC3_BP      206616          C3002     C3002CSC3  biopsy_16S
...            ...         ...            ...           ...         ...
5528   P6038C7_MVX    PSMA2675          P6038       P6038C7    viromics
5529   P6038C8_MVX    PSMA269S          P6038       P6038C8    viromics
5530  P6038C10_MVX    PSMA269W          P6038      P6038C10    viromics
5531  P6038C13_MVX    PSMA26A3          P6038      P6038C13    viromics
5532  P6038C19_MVX    PSMB4MC5          P6038      P6038C19    viromics

      week_num date_of_receipt  interval_days  visit_num Research Project  \
0          2.0             NaN            NaN          1           ibdmdb
1          2.0             NaN            NaN          1           ibdmdb
2          0.0             NaN            NaN          1           ibdmdb
3          0.0             NaN            NaN          1           ibdmdb
4          0.0             NaN            NaN          1           ibdmdb
...        ...             ...            ...        ...              ...
5528      13.0      2016-02-17           14.0         11           ibdmdb
5529      15.0      2016-03-01           13.0         12           ibdmdb
5530      20.0      2016-04-01           11.0         14           ibdmdb
5531      26.0      2016-05-12           14.0         18           ibdmdb
5532      37.0      2016-08-03           14.0         25           ibdmdb

      ... FecalCal received at MGH:  Proteomics received at LBNL:  \
0     ...                        No                            No
1     ...                        No                            No
2     ...                        No                            No
3     ...                        No                            No
4     ...                        No                            No
...   ...                       ...                           ...
5528  ...                        No                            No
5529  ...                        No                            No
5530  ...                        No                            No
5531  ...                        No                            No
5532  ...                        No                            No

     Stool Sample ID:  Tube A  (EtOH) Sample ID: Tube B (No preservative)  \
0                                 NaN                                 NaN
1                                 NaN                                 NaN
2                                 NaN                                 NaN
3                                 NaN                                 NaN
4                                 NaN                                 NaN
...                               ...                                 ...
5528                         SM-A2675                            SM-A2676
5529                         SM-A269S                            SM-A269T
5530                         SM-A269W                            SM-A269X
5531                         SM-A26A3                            SM-A26A4
5532                         SM-B4MC5                            SM-B4MC6

     Tube A and B received at Broad:  stool_id  smoking status  \
0                                 No       NaN             NaN
1                                 No       NaN             NaN
2                                 No       NaN             NaN
3                                 No       NaN             NaN
4                                 No       NaN             NaN
...                              ...       ...             ...
5528                              No       NaN             NaN
5529                              No       NaN             NaN
5530                              No       NaN             NaN
5531                              No       NaN             NaN
5532                              No       NaN             NaN

      Number years smoked  Age when started smoking  \
0                     NaN                       NaN
1                     NaN                       NaN
2                     NaN                       NaN
3                     NaN                       NaN
4                     NaN                       NaN
...                   ...                       ...
5528                  NaN                       NaN
5529                  NaN                       NaN
5530                  NaN                       NaN
5531                  NaN                       NaN
5532                  NaN                       NaN

      How many cigarettes/cigars/etc. do you smoke per day?
0                                                   NaN
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
5528                                                NaN
5529                                                NaN
5530                                                NaN
5531                                                NaN
5532                                                NaN

[5533 rows x 490 columns]>

C:\Users\deepa\AppData\Local\Temp\ipykernel_6932\3662975295.py:3: DtypeWarning: Columns (12,13,14,40,46,55,65,66,67,68,177,294,298,299,300,301,304,305,306,307,308,309,310,318,320,328,330,346,348,350,352,354,359,361,363,366,373,377,381,383,418,419,432,433,434,435,436,438,439,440,441,442,444,445,446,447,448,450,451,452,453,454) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename)

In [5]:
df

,Project,External ID,Participant ID,site_sub_coll,data_type,week_num,date_of_receipt,interval_days,visit_num,Research Project,...,FecalCal received at MGH:,Proteomics received at LBNL:,Stool Sample ID: Tube A (EtOH),Sample ID: Tube B (No preservative),Tube A and B received at Broad:,stool_id,smoking status,Number years smoked,Age when started smoking,How many cigarettes/cigars/etc. do you smoke per day?
0,C3001CSC1_BP,206615,C3001,C3001CSC1,biopsy_16S,2.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
1,C3001CSC2_BP,206614,C3001,C3001CSC2,biopsy_16S,2.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
2,C3002CSC1_BP,206617,C3002,C3002CSC1,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
3,C3002CSC2_BP,206619,C3002,C3002CSC2,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
4,C3002CSC3_BP,206616,C3002,C3002CSC3,biopsy_16S,0.0,NaN,NaN,1,ibdmdb,...,No,No,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,P6038C7_MVX,PSMA2675,P6038,P6038C7,viromics,13.0,2016-02-17,14.0,11,ibdmdb,...,No,No,SM-A2675,SM-A2676,No,NaN,NaN,NaN,NaN,NaN
5529,P6038C8_MVX,PSMA269S,P6038,P6038C8,viromics,15.0,2016-03-01,13.0,12,ibdmdb,...,No,No,SM-A269S,SM-A269T,No,NaN,NaN,NaN,NaN,NaN
5530,P6038C10_MVX,PSMA269W,P6038,P6038C10,viromics,20.0,2016-04-01,11.0,14,ibdmdb,...,No,No,SM-A269W,SM-A269X,No,NaN,NaN,NaN,NaN,NaN
5531,P6038C13_MVX,PSMA26A3,P6038,P6038C13,viromics,26.0,2016-05-12,14.0,18,ibdmdb,...,No,No,SM-A26A3,SM-A26A4,No,NaN,NaN,NaN,NaN,NaN
5532,P6038C19_MVX,PSMB4MC5,P6038,P6038C19,viromics,37.0,2016-08-03,14.0,25,ibdmdb,...,No,No,SM-B4MC5,SM-B4MC6,No,NaN,NaN,NaN,NaN,NaN

In [6]:
meta_data=df[['External ID','diagnosis']]
meta_data

     External ID diagnosis
0         206615        CD
1         206614        CD
2         206617        CD
3         206619        CD
4         206616        CD
...          ...       ...
5528    PSMA2675        UC
5529    PSMA269S        UC
5530    PSMA269W        UC
5531    PSMA26A3        UC
5532    PSMB4MC5        UC

[5533 rows x 2 columns]

In [10]:
meta_data.diagnosis.value_counts()

CD        2682
UC        1506
nonIBD    1345
Name: diagnosis, dtype: int64

In [12]:
filename=os.path.join(dir,"NIH_data\\taxonomic_profiles.tsv")
otu=pd.read_csv(filename, sep="\t").T
otu

,0,1,2,3,4,5,6,7,8,9,...,972,973,974,975,976,977,978,979,980,981
#OTU ID,IP8BSoli,UncTepi3,Unc004ii,Unc00re8,Unc018j2,Unc04u81,Unc58370,Unc05fip,Unc02ae9,GV2Pseu5,...,Unc01oix,Unc02eb1,UncB1465,UncAl534,Unc63248,Unc01505,Unc27462,Unc00bs1,Unc002ze,UncRumi6
206646,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,481.0,0.0,0.0,0.0,0.0
224324,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0
206619,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
224326,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,117.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206718,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0
206657,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0
206670,0.0,10.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,228.0,0.0,4.0,0.0,0.0
206655,0.0,0.0,36.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
taxonomy,Bacteria; __Proteobacteria; __Alphaproteobacte...,Bacteria; __Proteobacteria; __Betaproteobacter...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Bacteroidetes; __Bacteroidia; __Ba...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Proteobacteria; __Alphaproteobacte...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Proteobacteria; __Gammaproteobacte...,Bacteria; __Proteobacteria; __Gammaproteobacte...,Bacteria; __Actinobacteria; __Actinobacteria; ...,...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Bacteroidetes; __Bacteroidia; __Ba...,Bacteria; __Tenericutes; __Mollicutes; __Molli...,Bacteria; __Proteobacteria; __Alphaproteobacte...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Bacteroidetes; __Sphingobacteriia;...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Firmicutes; __Clostridia; __Clostr...,Bacteria; __Firmicutes; __Clostridia; __Clostr...

In [16]:
data= pd.merge(meta_data,otu,left_on=['External ID'], right_index=True)

In [17]:
data

,External ID,diagnosis,0,1,2,3,4,5,6,7,...,972,973,974,975,976,977,978,979,980,981
0,206615,CD,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,366.0,0.0,0.0,0.0,0.0
1,206614,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,193.0,0.0,0.0,0.0,0.0
2,206617,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,206619,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0
4,206616,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,219669,UC,0.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,103.0,0.0,0.0,0.0,0.0
174,219675,CD,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
175,219676,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
176,219691,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0
177,219692,CD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
data.diagnosis.value_counts()

CD        86
UC        46
nonIBD    46
Name: diagnosis, dtype: int64